export const incompatibleFonts = [
  "Allkin",
  "Chiron GoRound TC",
  "Chiron Sung HK",
  "Chiron Hei HK",
  "Linefont",
  "Material Icons",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "Material Symbols",
  "Material Symbols Outlined",
  "Material Symbols Rounded",
  "Material Symbols Sharp",
  "Playwrite AR",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD Guides",
  "Playwrite AU QLD",
  "Playwrite AU SA",
  "Playwrite AU SA Guides",
  "Playwrite AU TAS",
  "Playwrite AU VIC",
  "Playwrite AU TAS Guides",
  "Playwrite BE VLG",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL Guides",
  "Playwrite AU VIC Guides",
  "Playwrite BE WAL",
  "Playwrite BR",
  "Playwrite BR Guides",
  "Playwrite CA Guides",
  "Playwrite CL",
  "Playwrite CL Guides",
  "Playwrite CO",
  "Playwrite CA",
  "Playwrite CU",
  "Playwrite CO Guides",
  "Playwrite CU Guides",
  "Playwrite CZ",
  "Playwrite CZ Guides",
  "Playwrite DE Grund",
  "Playwrite DE Grund Guides",
  "Playwrite DE LA",
  "Playwrite DE LA Guides",
  "Playwrite DE SAS",
  "Playwrite DE SAS Guides",
  "Playwrite DE VA",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet Guides",
  "Playwrite DK Uloopet Guides",
  "Playwrite DK Loopet",
  "Playwrite ES",
  "Playwrite ES Deco",
  "Playwrite ES Guides",
  "Playwrite ES Deco Guides",
  "Playwrite FR Moderne",
  "Playwrite FR Trad",
  "Playwrite FR Trad Guides",
  "Playwrite GB J",
  "Playwrite GB J Guides",
  "Playwrite GB S",
  "Playwrite FR Moderne Guides",
  "Playwrite GB S Guides",
  "Playwrite HR",
  "Playwrite HR Guides",
  "Playwrite HR Lijeva",
  "Playwrite HR Lijeva Guides",
  "Playwrite HU",
  "Playwrite IE",
  "Playwrite IE Guides",
  "Playwrite ID Guides",
  "Playwrite IN",
  "Playwrite IN Guides",
  "Playwrite HU Guides",
  "Playwrite ID",
  "Playwrite IS Guides",
  "Playwrite IT Moderna",
  "Playwrite IS",
  "Playwrite IT Trad",
  "Playwrite IT Trad Guides",
  "Playwrite IT Moderna Guides",
  "Playwrite MX",
  "Playwrite MX Guides",
  "Playwrite NG Modern",
  "Playwrite NG Modern Guides",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NO Guides",
  "Playwrite NO",
  "Playwrite NZ Basic",
  "Playwrite NZ Basic Guides",
  "Playwrite NZ Guides",
  "Playwrite PE",
  "Playwrite PE Guides",
  "Playwrite PL",
  "Playwrite NZ",
  "Playwrite PT",
  "Playwrite PL Guides",
  "Playwrite PT Guides",
  "Playwrite RO",
  "Playwrite RO Guides",
  "Playwrite TZ",
  "Playwrite SK",
  "Playwrite SK Guides",
  "Playwrite TZ Guides",
  "Playwrite US Modern Guides",
  "Playwrite US Trad",
  "Playwrite US Modern",
  "Playwrite VN",
  "Playwrite VN Guides",
  "Playwrite US Trad Guides",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Playwrite DK Uloopet",
  "Wavefont"
];